spring:
  datasource:
    #url: jdbc:mysql://scenect-db.ctwqsim6sg2z.ap-northeast-2.rds.amazonaws.com:3306/scenect?serverTimezone=Asia/Seoul
    #username: admin
    #password: Zerocola00!
    url: jdbc:mysql://localhost:3306/scenect
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

  jwt:
    secret: tpzbatpasdkbfqkdlakjsdkfasldfkjsfkasgnanwifk
    expiration: 86400000 # 1 day
    header: Authorization
    prefix: Bearer
    issuer: SecurityJWT
    audience: SecurityJWT

